---
- name: Import facts
  ansible.builtin.import_role:
    name: k3s
    tasks_from: facts

- name: Install Dependencies
  tags: deps
  when: ansible_host in k3s_server_hosts
  block:
    - name: Set binary fact
      ansible.builtin.set_fact:
        binary:
          - org: cilium
            repo: cilium-cli
            version: '{{ cilium_vars.cli.version }}'
            name: '{{ cilium_vars.cli.name }}'
          - org: cilium
            repo: hubble
            version: '{{ cilium_vars.hubble.version }}'
            name: '{{ cilium_vars.hubble.name }}'
      run_once: true

    - name: Download archive
      ansible.builtin.get_url:
        url: https://github.com/{{ item.org }}/{{ item.repo }}/releases/download/{{ item.version }}/{{ item.name }}
        checksum: sha256:https://github.com/{{ item.org }}/{{ item.repo }}/releases/download/{{ item.version }}/{{ item.name }}.sha256sum
        dest: /tmp
        owner: root
        group: root
        mode: '0644'
      loop: '{{ binary }}'
      register: result
      delay: 1
      retries: 3
      until: result is not failed

    - name: Install binary
      ansible.builtin.unarchive:
        src: /tmp/{{ item.name }}
        dest: /usr/local/bin
        owner: root
        group: root
        mode: '0755'
        remote_src: true
      loop: '{{ binary }}'

    - name: Delete archive
      ansible.builtin.file:
        path: /tmp/{{ item.name }}
        state: absent
      loop: '{{ binary }}'

    - name: Add repository
      kubernetes.core.helm_repository:
        name: '{{ cilium_vars.kubernetes.helm.repository.name }}'
        repo_url: '{{ cilium_vars.kubernetes.helm.repository.url }}'

- name: Chart Setup
  tags: chart
  when: ansible_host == k3s_server_default_host
  block:
    - name: Apply gateway api crds manifest
      kubernetes.core.k8s:
        kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
        src: https://github.com/kubernetes-sigs/gateway-api/releases/download/{{ cilium_vars.kubernetes.gateway_api.version }}/experimental-install.yaml

    - name: Install chart
      kubernetes.core.helm:
        chart_ref: '{{ cilium_vars.kubernetes.helm.repository.name }}/{{ cilium_vars.kubernetes.helm.chart.name }}'
        chart_version: '{{ cilium_vars.kubernetes.helm.chart.version }}'
        kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
        name: '{{ cilium_vars.kubernetes.helm.chart.name }}'
        namespace: '{{ cilium_vars.kubernetes.namespace }}'
        update_repo_cache: true
        values:
          bandwidthManager:
            enabled: true
          enableCiliumEndpointSlice: true
          envoy:
            enabled: true
            resources:
              limits:
                cpu: '{{ cilium_vars.kubernetes.envoy.resources.limits.cpu }}'
                memory: '{{ cilium_vars.kubernetes.envoy.resources.limits.memory }}'
              requests:
                cpu: '{{ cilium_vars.kubernetes.envoy.resources.requests.cpu }}'
                memory: '{{ cilium_vars.kubernetes.envoy.resources.requests.memory }}'
            rollOutPods: true
          externalIPs:
            enabled: true
          gatewayAPI:
            enabled: true
          ipam:
            operator:
              clusterPoolIPv4PodCIDRList: '{{ cilium_vars.kubernetes.ipam.operator.cluster.pool }}'
          hubble:
            peerService:
              clusterDomain: '{{ k3s_vars.cluster.domain }}'
            relay:
              enabled: true
              replicas: '{{ cilium_vars.kubernetes.hubble.relay.replicas }}'
              resources:
                limits:
                  cpu: '{{ cilium_vars.kubernetes.hubble.relay.resources.limits.cpu }}'
                  memory: '{{ cilium_vars.kubernetes.hubble.relay.resources.limits.memory }}'
                requests:
                  cpu: '{{ cilium_vars.kubernetes.hubble.relay.resources.requests.cpu }}'
                  memory: '{{ cilium_vars.kubernetes.hubble.relay.resources.requests.memory }}'
              retryTimeout: '{{ cilium_vars.kubernetes.hubble.relay.retry_timeout }}'
              rollOutPods: true
            ui:
              enabled: true
              rollOutPods: true
          k8sClientRateLimit:
            burst: '{{ cilium_vars.kubernetes.client.rate_limit.burst }}'
            qps: '{{ cilium_vars.kubernetes.client.rate_limit.qps }}'
          k8sServiceHost: '{{ k3s_vars.loadbalancer.server.host }}'
          k8sServicePort: '{{ k3s_vars.loadbalancer.server.port }}'
          kubeProxyReplacement: true
          operator:
            resources:
              limits:
                cpu: '{{ cilium_vars.kubernetes.operator.resources.limits.cpu }}'
                memory: '{{ cilium_vars.kubernetes.operator.resources.limits.memory }}'
              requests:
                cpu: '{{ cilium_vars.kubernetes.operator.resources.requests.cpu }}'
                memory: '{{ cilium_vars.kubernetes.operator.resources.requests.memory }}'
            rollOutPods: true
          rollOutCiliumPods: true
        wait: true
      register: result
      delay: 1
      retries: 3
      until: result is not failed

    - name: Create l2 announcement policy
      kubernetes.core.k8s:
        definition:
          apiVersion: cilium.io/v2alpha1
          kind: CiliumL2AnnouncementPolicy
          metadata:
            name: default-l2-announcement-policy
            namespace: '{{ cilium_vars.kubernetes.namespace }}'
          spec:
            externalIPs: true
            interfaces:
              - '{{ k3s_vars.network.interface }}'
            loadBalancerIPs: true
        kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
        wait: true

    - name: Create loadbalancer ip pool
      kubernetes.core.k8s:
        definition:
          apiVersion: cilium.io/v2alpha1
          kind: CiliumLoadBalancerIPPool
          metadata:
            name: default-pool
            namespace: '{{ cilium_vars.kubernetes.namespace }}'
          spec:
            cidrs:
              - cidr: '{{ cilium_vars.kubernetes.loadbalancer.ip.pool }}'
        kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
        wait: true

    - name: Set ingress controller
      kubernetes.core.helm:
        chart_ref: '{{ cilium_vars.kubernetes.helm.repository.name }}/{{ cilium_vars.kubernetes.helm.chart.name }}'
        chart_version: '{{ cilium_vars.kubernetes.helm.chart.version }}'
        kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
        name: '{{ cilium_vars.kubernetes.helm.chart.name }}'
        namespace: '{{ cilium_vars.kubernetes.namespace }}'
        reset_values: false
        reuse_values: true
        values:
          ingressController:
            enabled: true
            service:
              loadBalancerIP: '{{ cilium_vars.kubernetes.ingress.controller.service.loadbalancer.ip }}'
        wait: true
      register: result
      delay: 1
      retries: 3
      until: result is not failed

    - name: Set loadbalancer algorithm
      kubernetes.core.helm:
        chart_ref: '{{ cilium_vars.kubernetes.helm.repository.name }}/{{ cilium_vars.kubernetes.helm.chart.name }}'
        chart_version: '{{ cilium_vars.kubernetes.helm.chart.version }}'
        kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
        name: '{{ cilium_vars.kubernetes.helm.chart.name }}'
        namespace: '{{ cilium_vars.kubernetes.namespace }}'
        reset_values: false
        reuse_values: true
        values:
          loadBalancer:
            algorithm: '{{ cilium_vars.kubernetes.loadbalancer.algorithm }}'
          maglev:
            hashSeed: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_letters', 'digits'], length=12) }}"
            tableSize: '{{ cilium_vars.kubernetes.loadbalancer.table_size }}'
        wait: true
      register: result
      delay: 1
      retries: 3
      until: result is not failed
      when: cilium_vars.kubernetes.loadbalancer.algorithm == 'maglev'

    - name: Set routing mode
      kubernetes.core.helm:
        chart_ref: '{{ cilium_vars.kubernetes.helm.repository.name }}/{{ cilium_vars.kubernetes.helm.chart.name }}'
        chart_version: '{{ cilium_vars.kubernetes.helm.chart.version }}'
        kubeconfig: '{{ k3s_vars.directory.config }}/k3s.yaml'
        name: '{{ cilium_vars.kubernetes.helm.chart.name }}'
        namespace: '{{ cilium_vars.kubernetes.namespace }}'
        reset_values: false
        reuse_values: true
        values:
          autoDirectNodeRoutes: true
          ipv4NativeRoutingCIDR: '{{ cilium_vars.kubernetes.ipam.operator.cluster.pool }}'
          l2announcements:
            enabled: true
          l2podAnnouncements:
            enabled: true
            interface: '{{ k3s_vars.network.interface }}'
          routingMode: '{{ cilium_vars.kubernetes.routing_mode }}'
        wait: true
      register: result
      delay: 1
      retries: 3
      until: result is not failed
      when: cilium_vars.kubernetes.routing_mode == 'native'
